version: "3"
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:8080"
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
